# Generated by Django 3.2 on 2023-06-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
