# Generated by Django 3.2 on 2023-06-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0002_client_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='appointment',
        ),
        migrations.AddField(
            model_name='client',
            name='appoint_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='appoint_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
