# Generated by Django 3.2 on 2023-06-30 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0003_auto_20230630_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='stylist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='stylist.stylist'),
        ),
    ]
