# Generated by Django 3.2 on 2023-06-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0004_alter_client_stylist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('stylist', 'name')},
        ),
    ]
