# Generated by Django 3.2 on 2023-06-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0005_alter_client_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['appoint_date']},
        ),
    ]
