# Generated by Django 3.2 on 2023-06-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0006_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['appoint_date', 'appoint_time']},
        ),
    ]
