# Generated by Django 3.2 on 2023-07-06 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0007_alter_client_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc', to='stylist.judet')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stylist.loc'),
        ),
    ]
