# Generated by Django 3.2 on 2023-07-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0008_auto_20230706_0719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['appoint_date', 'appoint_time']},
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('stylist', 'name')},
        ),
    ]
