# Generated by Django 3.2 on 2023-07-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0009_auto_20230706_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_loc', to='stylist.loc'),
        ),
    ]
