# Generated by Django 3.2 on 2023-07-07 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0011_alter_client_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loc',
            name='jud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='stylist.judet'),
        ),
    ]
