# Generated by Django 3.2 on 2023-07-08 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0012_alter_loc_jud'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='jud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jud', to='stylist.judet'),
        ),
    ]
