# Generated by Django 3.2 on 2023-07-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0013_client_jud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='jud',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='loc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
