# Generated by Django 3.2 on 2023-06-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.ManyToManyField(related_name='books', to='todo.Comment'),
        ),
    ]
