# Generated by Django 3.2 on 2023-06-17 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0009_alter_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='like',
            field=models.ManyToManyField(related_name='book_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
