# Generated by Django 3.2 on 2023-06-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_book_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='like',
        ),
    ]
