# Generated by Django 3.2 on 2023-06-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_remove_book_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
