# Generated by Django 3.2 on 2023-06-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_like_unique_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
