# Generated by Django 3.2 on 2023-06-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_auto_20230618_0806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
