# Generated by Django 3.2 on 2023-06-18 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0018_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='book', to=settings.AUTH_USER_MODEL),
        ),
    ]
