# Generated by Django 3.2 on 2023-06-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_product_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='products', to='menu.Ingredient'),
        ),
    ]
