# Generated by Django 3.2 on 2023-06-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20230622_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='ingredients', to='menu.Product'),
        ),
    ]
