# Generated by Django 3.2 on 2023-06-22 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_stars',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
