# Generated by Django 3.2 on 2023-06-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_product_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review_stars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
