# Generated by Django 3.2 on 2023-06-22 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_product_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review_stars',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.product')),
            ],
        ),
    ]
